//HintName: EndpointExample.EndpointExtension.g.cs
// <auto-generated />
using Microsoft.OpenApi;
using System.Text.Json;

namespace EndpointExample;

/// <summary>
/// 	
/// </summary>
public static class EndpointExampleExtension
{
     /// <summary>
     /// 	
     /// </summary>
     public static readonly IReadOnlyList<KeyValuePair<Type, (string ExampleName, object ExampleRecord)>> Examples = 
     [
         //CreateUserExample
         new (typeof(CreateUserExample), ("NormalCheck", global::WebApi.Endpoint.User.CreateUser.UserCreateExample.NormalCheck)),

         //CreateUserExample
         new (typeof(CreateUserExample), ("SourceGeneratedCheck", global::WebApi.Endpoint.User.CreateUser.UserCreateExample.SourceGeneratedCheck)),

     ];
}
