using System.Text;

namespace MinimalApiRegistration;

public static class SourceGenerationHelper
{
    public const string Namespace = nameof(MinimalApiRegistration);
    public const string ContextName = "Endpoint";

    public const string Attribute =
        $$"""
          // <auto-generated />
          namespace {{Namespace}};

          /// <summary>
          ///		Marker for specifying endpoints that will be mapped using custom source generator
          /// </summary>
          [System.AttributeUsage(System.AttributeTargets.Class)]
          public class {{ContextName}}Attribute : System.Attribute
          {
          }
          """;

    public const string Extension =
        $$"""
          // <auto-generated />
          namespace {{Namespace}};

          /// <summary>
          ///	Helper extensions for endpoints registration
          /// </summary>
          public static class {{ContextName}}Extensions
          {
          	/// <summary>
          	///		Returns endpoint file namespace
          	/// </summary>
          	public static string Namespace(this Type type) => string.Join("/", type.Namespace?.Split('.')[2..]!);
          }
          """;

    public const string ExtensionClassPrefixCode =
        $$"""
          // <auto-generated />
          namespace {{Namespace}};

          /// <summary>
          /// 	Generated mappings of endpoints
          /// </summary>
          public static class EndpointsExtension
          {
          """;

    public const string ExtensionClassSuffixCode =
        """
        }
        """;

    public const string MapAllEndpointsPrefixCode =
        """
             /// <summary>
             /// 	Register endpoints
             /// </summary>
             public static IEndpointRouteBuilder MapAllEndpoints(this IEndpointRouteBuilder builder)
             {
        """;

    public const string MapAllEndpointsSuffixCode =
        """
                 return builder;
             }
        """;

    internal static StringBuilder AppendEndpointRegistration(this StringBuilder codeBuilder, EndpointDefinition definition)
    {
        codeBuilder.AppendLine($"         //{definition.Name}");
        codeBuilder.AppendLine($"         {definition.FullNamespace}");
        codeBuilder.AppendLine($"               .MapEndpoint(builder, typeof({definition.FullNamespace}).Namespace())");
        codeBuilder.AppendLine($"""               .WithTags("{definition.Group}")""");
        codeBuilder.AppendLine("               .Produces(StatusCodes.Status401Unauthorized, responseType: typeof(void), contentType: null);");
        codeBuilder.AppendLine();

        return codeBuilder;
    }
}
