//HintName: MinimalApiRegistration.EndpointExtension.g.cs
// <auto-generated />
namespace MinimalApiRegistration;

/// <summary>
/// 	Generated mappings of endpoints
/// </summary>
public static class EndpointsExtension
{
     /// <summary>
     /// 	Register endpoints
     /// </summary>
     public static IEndpointRouteBuilder MapAllEndpoints(this IEndpointRouteBuilder builder)
     {
         //CreateUser
         global::WebApi.Endpoints.User.CreateUser.Endpoint
               .MapEndpoint(builder, typeof(global::WebApi.Endpoints.User.CreateUser.Endpoint).Namespace())
               .WithTags("User")
               .Produces(StatusCodes.Status401Unauthorized, responseType: typeof(void), contentType: null);

         return builder;
     }
}
