//HintName: MinimalApiRegistration.NameExtensions.g.cs
// <auto-generated />
namespace MinimalApiRegistration;

/// <summary>
///	Helper extensions for endpoints registration
/// </summary>
public static class EndpointExtensions
{
	/// <summary>
	///		Returns endpoint file namespace
	/// </summary>
	public static string Namespace(this Type type) => string.Join("/", type.Namespace?.Split('.')[2..]!);
}