namespace EndpointExample;

public static class SourceGenerationHelper
{
    public const string ContextName = "EndpointExample";
    public const string Namespace = nameof(EndpointExample);

    public const string Attribute =
        $$"""
          // <auto-generated />
          namespace {{Namespace}};

          /// <summary>
          ///		Marker for specifying endpoint examples that will be mapped using custom source generator
          /// </summary>
          #nullable enable
          [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Method | System.AttributeTargets.Property)]
          public class {{ContextName}}Attribute(string? exampleName = null) : System.Attribute
          {
          	/// <summary>
          	///		
          	/// </summary>
          	public string? ExampleName { get; } = exampleName;
          }
          #nullable disable
          """;

    public const string ExtensionClassPrefixCode =
        $$"""
          // <auto-generated />
          using Microsoft.OpenApi;
          using System.Text.Json;

          namespace {{Namespace}};

          /// <summary>
          /// 	
          /// </summary>
          public static class {{ContextName}}Extension
          {
          	 #nullable enable
          	 private static List<Type>? _availableTypes;
          	 
          	 /// <summary>
          	 ///		
          	 /// </summary>
          	 public static List<Type> AvailableTypes =>
          		 _availableTypes ??= Examples
          		     .Select(x => x.Key)
          		     .Distinct()
          		     .ToList();
               #nullable disable
               
               /// <summary>
               /// 	
               /// </summary>
               public static readonly IReadOnlyList<KeyValuePair<Type, (string ExampleName, object ExampleRecord)>> Examples = 
               [
          """;

    public const string ExtensionClassSuffixCode =
        """
             ];
        }
        """;
}